config/routes.rb
Salesforce::Application.routes.draw do
  resources :yelps

end

app/models/yelp.rb
class Yelp < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/yelps_controller.rb
class YelpsController < ApplicationController
  before_action :set_yelp, only: [:show, :edit, :update, :destroy]

  # GET /yelps
  # GET /yelps.json
  def index
    @yelps = Yelp.all
  end

  # GET /yelps/1
  # GET /yelps/1.json
  def show
  end

  # GET /yelps/new
  def new
    @yelp = Yelp.new
  end

  # GET /yelps/1/edit
  def edit
  end

  # POST /yelps
  # POST /yelps.json
  def create
    @yelp = Yelp.new(yelp_params)

    respond_to do |format|
      if @yelp.save
        format.html { redirect_to @yelp, notice: 'Yelp was successfully created.' }
        format.json { render action: 'show', status: :created, location: @yelp }
      else
        format.html { render action: 'new' }
        format.json { render json: @yelp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yelps/1
  # PATCH/PUT /yelps/1.json
  def update
    respond_to do |format|
      if @yelp.update(yelp_params)
        format.html { redirect_to @yelp, notice: 'Yelp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @yelp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yelps/1
  # DELETE /yelps/1.json
  def destroy
    @yelp.destroy
    respond_to do |format|
      format.html { redirect_to yelps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yelp
      @yelp = Yelp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yelp_params
      params.require(:yelp).permit(:name, :address, :descr, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/yelps_helper.rb
module YelpsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Salesforce</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/yelps/_form.html.erb
<%= form_for(@yelp) do |f| %>
  <% if @yelp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yelp.errors.count, "error") %> prohibited this yelp from being saved:</h2>

      <ul>
      <% @yelp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :descr %><br>
    <%= f.text_area :descr %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yelps/edit.html.erb
<h1>Editing yelp</h1>

<%= render 'form' %>

<%= link_to 'Show', @yelp %> |
<%= link_to 'Back', yelps_path %>

app/views/yelps/index.html.erb
<h1>Listing yelps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Descr</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @yelps.each do |yelp| %>
      <tr>
        <td><%= yelp.name %></td>
        <td><%= yelp.address %></td>
        <td><%= yelp.descr %></td>
        <td><%= yelp.comment %></td>
        <td><%= link_to 'Show', yelp %></td>
        <td><%= link_to 'Edit', edit_yelp_path(yelp) %></td>
        <td><%= link_to 'Destroy', yelp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yelp', new_yelp_path %>

app/views/yelps/new.html.erb
<h1>New yelp</h1>

<%= render 'form' %>

<%= link_to 'Back', yelps_path %>

app/views/yelps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @yelp.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @yelp.address %>
</p>

<p>
  <strong>Descr:</strong>
  <%= @yelp.descr %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @yelp.comment %>
</p>

<%= link_to 'Edit', edit_yelp_path(@yelp) %> |
<%= link_to 'Back', yelps_path %>